---
- name: Load OS specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_os_family|lower }}.yml"
        - defaults.yml
      paths:
        - ../vars

- name: Download the Ambari repo
  get_url: url={{ ambari_repo }} dest={{ ambari_repo_file }}

- name: Add apt key
  apt_key: keyserver=keyserver.ubuntu.com id={{ ambari_repo_key }}
  when: ansible_os_family == "Debian"

- name: Ensure required packages are installed (yum)
  yum:
    name: "{{ item }}"
    update_cache: yes
    state: installed
  with_items:
    - ambari-agent
  when: ansible_os_family == "RedHat"

- name: Ensure required packages are installed (apt)
  apt:
    name: "{{ item }}"
    update_cache: yes
    state: installed
  with_items:
    - ambari-agent
  when: ansible_os_family == "Debian"

- name: Configure the Ambari agent
  lineinfile: dest=/etc/ambari-agent/conf/ambari-agent.ini
              regexp='^hostname='
              line='hostname={{ hostvars[groups['ambari-node'][0]]['ansible_fqdn'] }}'
              state=present

- name: Make sure ambari-agent is running
  service: name=ambari-agent state=started enabled=yes
