---
- name: "Show debug info"
  hosts: all-nodes
  tasks:
    - name: "Show all-nodes info"
      debug: var=hostvars[inventory_hostname]
      when: debug

- name: "Apply the ambari-agent role to all nodes"
  hosts: all-nodes
  any_errors_fatal: true
  roles:
    - ambari-agent
  tags:
    - ambari-agent-only

- name: "Apply the mysql role to ambari nodes"
  hosts: master-nodes
  vars_files:
    - group_vars/rangerdb.yml
  roles:
    - { role: geerlingguy.mysql }


- name: "Apply the ranger role to ambari nodes"
  hosts: master-nodes
  any_errors_fatal: true
  roles:
    - ranger
  tags:
    - ranger-only


- name: "Apply the ambari-server role to ambari-node group"
  hosts: master-nodes
  roles:
    - ambari-server
  tags:
   - ambari-server-only
